services:
  jobhire-gateway:
    container_name: jobhire-gateway
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - 5001:5001
    networks:
      - local_network

networks:
  local_network: