services:
  jobhire-gateway:
    container_name: jobhire-gateway
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5001:5001
    restart: on-failure